/**
 * Canonical genre whitelist for Last.fm tag filtering.
 *
 * Tags from Last.fm are filtered against this whitelist to ensure
 * only recognized music genres are stored (not moods, years, etc).
 */

export const GENRE_WHITELIST: ReadonlySet<string> = new Set([
	// === ROCK & SUBGENRES ===
	"rock",
	"alternative rock",
	"alt rock",
	"alternative",
	"indie rock",
	"indie",
	"classic rock",
	"hard rock",
	"soft rock",
	"progressive rock",
	"prog rock",
	"prog",
	"progressive",
	"psychedelic rock",
	"psychedelic",
	"punk rock",
	"punk",
	"post-punk",
	"post punk",
	"post-rock",
	"post rock",
	"art rock",
	"garage rock",
	"garage",
	"grunge",
	"shoegaze",
	"dream pop",
	"noise rock",
	"noise",
	"noise pop",
	"stoner rock",
	"stoner",
	"southern rock",
	"blues rock",
	"folk rock",
	"folk-rock",
	"country rock",
	"glam rock",
	"glam",
	"new wave",
	"britpop",
	"krautrock",
	"space rock",
	"surf",
	"rockabilly",
	"rock and roll",
	"rock n roll",
	"emo",
	"emocore",
	"screamo",
	"post-hardcore",
	"post hardcore",
	"math rock",
	"midwest emo",
	"pop punk",
	"pop rock",
	"pop-rock",
	"power pop",
	"powerpop",
	"post-grunge",
	"experimental rock",
	"neo-psychedelia",

	// === METAL & SUBGENRES ===
	"metal",
	"heavy metal",
	"black metal",
	"death metal",
	"thrash metal",
	"thrash",
	"doom metal",
	"doom",
	"progressive metal",
	"power metal",
	"speed metal",
	"nu metal",
	"nu-metal",
	"metalcore",
	"deathcore",
	"djent",
	"groove metal",
	"groove",
	"sludge metal",
	"sludge",
	"gothic metal",
	"gothic rock",
	"gothic",
	"goth",
	"symphonic metal",
	"folk metal",
	"viking metal",
	"pagan metal",
	"industrial metal",
	"grindcore",
	"goregrind",
	"melodic death metal",
	"technical death metal",
	"brutal death metal",
	"blackened death metal",
	"atmospheric black metal",
	"depressive black metal",
	"raw black metal",
	"symphonic black metal",
	"melodic black metal",
	"death doom metal",
	"avant-garde metal",
	"alternative metal",
	"nwobhm",
	"glam metal",
	"hair metal",
	"crust",
	"mathcore",
	"melodic metalcore",
	"melodic hardcore",
	"melodic metal",
	"melodic rock",
	"melodic",
	"female fronted metal",
	"hardcore punk",
	"hardcore",
	"horror punk",
	"psychobilly",
	"deathrock",

	// === ELECTRONIC & SUBGENRES ===
	"electronic",
	"electronica",
	"edm",
	"house",
	"deep house",
	"tech house",
	"progressive house",
	"electro house",
	"electro",
	"techno",
	"minimal techno",
	"minimal",
	"trance",
	"psytrance",
	"progressive trance",
	"uplifting trance",
	"vocal trance",
	"goa",
	"dubstep",
	"drum and bass",
	"drum n bass",
	"dnb",
	"jungle",
	"breakbeat",
	"breaks",
	"breakcore",
	"uk garage",
	"grime",
	"ambient",
	"dark ambient",
	"drone",
	"idm",
	"glitch",
	"industrial",
	"ebm",
	"dark electro",
	"electro-industrial",
	"synthwave",
	"retrowave",
	"synthpop",
	"synth pop",
	"electropop",
	"futurepop",
	"chillwave",
	"downtempo",
	"trip-hop",
	"trip hop",
	"chillout",
	"chill out",
	"lounge",
	"nu-disco",
	"disco",
	"eurodance",
	"hardstyle",
	"hard trance",
	"gabber",
	"big beat",
	"acid",
	"acid jazz",
	"electroclash",
	"indietronica",
	"chiptune",
	"8-bit",
	"new rave",
	"rave",
	"club",
	"dance",
	"dancehall",
	"dub",
	"psychill",
	"new age",
	"beats",
	"trap",

	// === HIP-HOP & RAP ===
	"hip-hop",
	"hip hop",
	"hiphop",
	"rap",
	"gangsta rap",
	"underground hip-hop",
	"underground hip hop",
	"instrumental hip-hop",
	"rapcore",
	"drill",
	"uk drill",
	"boom bap",
	"lo-fi hip hop",
	"cloud rap",
	"conscious hip-hop",
	"alternative hip-hop",
	"east coast hip-hop",
	"west coast hip-hop",
	"southern hip-hop",
	"dirty south",
	"crunk",

	// === R&B & SOUL ===
	"rnb",
	"r&b",
	"soul",
	"neo-soul",
	"neo soul",
	"motown",
	"funk",
	"funky",
	"rhythm and blues",
	"gospel",
	"southern soul",
	"deep soul",
	"northern soul",
	"quiet storm",
	"new jack swing",
	"contemporary r&b",
	"alternative r&b",

	// === POP ===
	"pop",
	"indie pop",
	"synth-pop",
	"art pop",
	"chamber pop",
	"baroque pop",
	"jangle pop",
	"dance-pop",
	"europop",
	"k-pop",
	"kpop",
	"j-pop",
	"jpop",
	"c-pop",
	"latin pop",
	"hyperpop",
	"teen pop",

	// === JAZZ ===
	"jazz",
	"smooth jazz",
	"jazz fusion",
	"fusion",
	"bebop",
	"hard bop",
	"cool jazz",
	"free jazz",
	"avant-garde jazz",
	"modal jazz",
	"latin jazz",
	"nu jazz",
	"nu-jazz",
	"jazz rap",
	"swing",
	"big band",
	"contemporary jazz",
	"vocal jazz",
	"jazz vocal",
	"jazz piano",

	// === BLUES ===
	"blues",
	"electric blues",
	"delta blues",
	"chicago blues",
	"texas blues",
	"country blues",

	// === FOLK & COUNTRY ===
	"folk",
	"indie folk",
	"freak folk",
	"contemporary folk",
	"traditional folk",
	"traditional",
	"americana",
	"country",
	"alt-country",
	"outlaw country",
	"bluegrass",
	"newgrass",
	"old-time",
	"celtic",
	"irish folk",
	"scottish folk",
	"neofolk",
	"dark folk",
	"world",
	"world music",

	// === CLASSICAL & ORCHESTRAL ===
	"classical",
	"baroque",
	"romantic",
	"contemporary classical",
	"modern classical",
	"minimalism",
	"neoclassical",
	"orchestral",
	"opera",
	"choral",
	"chamber music",
	"soundtrack",
	"ost",
	"score",
	"film score",
	"video game music",
	"medieval",

	// === REGGAE & CARIBBEAN ===
	"reggae",
	"ska",
	"ska punk",
	"rocksteady",
	"roots reggae",
	"lovers rock",
	"ragga",
	"soca",
	"calypso",

	// === LATIN ===
	"latin",
	"salsa",
	"bachata",
	"merengue",
	"reggaeton",
	"latin trap",
	"bossa nova",
	"samba",
	"mpb",
	"tropicalia",
	"cumbia",
	"tango",
	"flamenco",
	"mariachi",
	"norteno",
	"banda",
	"tejano",

	// === ASIAN ===
	"j-rock",
	"jrock",
	"city pop",
	"shibuya-kei",
	"anime",
	"anisong",
	"visual kei",
	"asian pop",

	// === MIDDLE EASTERN & AFRICAN ===
	"arabic",
	"afrobeat",
	"afrobeats",
	"highlife",
	"afropop",
	"ethio-jazz",
	"desert blues",
	"gnawa",
	"rai",
	"ethnic",

	// === OTHER GENRES ===
	"singer-songwriter",
	"singer songwriter",
	"acoustic",
	"instrumental",
	"experimental",
	"avant-garde",
	"avantgarde",
	"lo-fi",
	"lofi",
	"easy listening",
	"dreamy",
	"ethereal",
	"atmospheric",
	"twee",
	"spoken word",
	"poetry",
	"comedy",
	"funny",
	"musical",
	"disney",
	"christmas",
	"christian",
	"christian rock",
	"worship",
	"spiritual",
	"darkwave",
	"coldwave",
	"ethereal wave",
	"power electronics",
	"martial industrial",
	"harsh noise",
	"urban",
	"crossover",
	"mashup",
	"groovy",
	"ballad",
	"oldies",
	"chanson",
	"chanson francaise",
	"schlager",
	"vocal",
]);

/**
 * Check if a tag is a recognized genre.
 * Performs case-insensitive lookup against the whitelist.
 */
export function isGenre(tag: string): boolean {
	return GENRE_WHITELIST.has(tag.toLowerCase());
}
