/**
 * Canonical genre whitelist for Last.fm tag filtering.
 *
 * Tags from Last.fm are filtered against this whitelist to ensure
 * only recognized music genres are stored (not moods, years, etc).
 */

const GENRE_WHITELIST: ReadonlySet<string> = new Set([
	// === ROCK & SUBGENRES ===
	"rock",
	"alternative rock",
	"alt rock",
	"alternative",
	"indie rock",
	"indie",
	"classic rock",
	"hard rock",
	"soft rock",
	"progressive rock",
	"prog rock",
	"prog",
	"progressive",
	"psychedelic rock",
	"psychedelic",
	"punk rock",
	"punk",
	"post-punk",
	"post punk",
	"post-rock",
	"post rock",
	"art rock",
	"garage rock",
	"garage",
	"grunge",
	"shoegaze",
	"dream pop",
	"noise rock",
	"noise",
	"noise pop",
	"stoner rock",
	"stoner",
	"southern rock",
	"blues rock",
	"folk rock",
	"folk-rock",
	"country rock",
	"glam rock",
	"glam",
	"new wave",
	"britpop",
	"krautrock",
	"space rock",
	"surf",
	"rockabilly",
	"rock and roll",
	"rock n roll",
	"emo",
	"emocore",
	"screamo",
	"post-hardcore",
	"post hardcore",
	"math rock",
	"midwest emo",
	"pop punk",
	"pop rock",
	"pop-rock",
	"power pop",
	"powerpop",
	"post-grunge",
	"experimental rock",
	"neo-psychedelia",
	"arena rock",
	"roots rock",
	"dance-rock",
	"symphonic rock",
	"celtic rock",
	"celtic punk",
	"bedroom pop",
	"sadcore",
	"slowcore",
	"cowpunk",
	"proto-punk",
	"garage rock revival",
	"garage punk",
	"anatolian rock",
	"flamenco rock",
	"math pop",

	// === METAL & SUBGENRES ===
	"metal",
	"heavy metal",
	"black metal",
	"death metal",
	"thrash metal",
	"thrash",
	"doom metal",
	"doom",
	"progressive metal",
	"power metal",
	"speed metal",
	"nu metal",
	"nu-metal",
	"metalcore",
	"deathcore",
	"djent",
	"groove metal",
	"groove",
	"sludge metal",
	"sludge",
	"gothic metal",
	"gothic rock",
	"gothic",
	"goth",
	"symphonic metal",
	"folk metal",
	"viking metal",
	"pagan metal",
	"industrial metal",
	"grindcore",
	"goregrind",
	"melodic death metal",
	"technical death metal",
	"brutal death metal",
	"blackened death metal",
	"atmospheric black metal",
	"depressive black metal",
	"raw black metal",
	"symphonic black metal",
	"melodic black metal",
	"death doom metal",
	"avant-garde metal",
	"alternative metal",
	"nwobhm",
	"glam metal",
	"hair metal",
	"crust",
	"mathcore",
	"stoner metal",
	"neo-classical metal",
	"proto-metal",
	"doom rock",
	"melodic metalcore",
	"melodic hardcore",
	"melodic metal",
	"melodic rock",
	"melodic",
	"female fronted metal",
	"hardcore punk",
	"hardcore",
	"horror punk",
	"psychobilly",
	"deathrock",

	// === ELECTRONIC & SUBGENRES ===
	"electronic",
	"electronica",
	"edm",
	"house",
	"deep house",
	"tech house",
	"progressive house",
	"electro house",
	"electro",
	"techno",
	"minimal techno",
	"minimal",
	"trance",
	"psytrance",
	"progressive trance",
	"uplifting trance",
	"vocal trance",
	"goa",
	"dubstep",
	"drum and bass",
	"drum n bass",
	"dnb",
	"jungle",
	"breakbeat",
	"breaks",
	"breakcore",
	"uk garage",
	"grime",
	"ambient",
	"dark ambient",
	"drone",
	"idm",
	"glitch",
	"industrial",
	"ebm",
	"dark electro",
	"electro-industrial",
	"synthwave",
	"retrowave",
	"synthpop",
	"synth pop",
	"electropop",
	"futurepop",
	"chillwave",
	"downtempo",
	"trip-hop",
	"trip hop",
	"chillout",
	"chill out",
	"lounge",
	"nu-disco",
	"disco",
	"eurodance",
	"hardstyle",
	"hard trance",
	"gabber",
	"big beat",
	"acid",
	"acid jazz",
	"electroclash",
	"indietronica",
	"chiptune",
	"8-bit",
	"new rave",
	"rave",
	"club",
	"dance",
	"dancehall",
	"dub",
	"psychill",
	"new age",
	"beats",
	"trap",

	// === ELECTRONIC SUBGENRES (EXTENDED) ===
	"hard-techno",
	"hard techno",
	"hardtechno",
	"acid house",
	"acid techno",
	"dark techno",
	"ambient techno",
	"ambient house",
	"future bass",
	"phonk",
	"amapiano",
	"afro house",
	"organic house",
	"uk bass",
	"hard dance",
	"deconstructed club",
	"glitchcore",
	"darksynth",
	"digicore",
	"tribal house",
	"new beat",
	"ghettotech",
	"freetekno",
	"future garage",
	"melodic dubstep",
	"neurofunk",
	"techstep",
	"liquidfunk",
	"trancecore",
	"loungetronica",
	"funktronica",

	// === HIP-HOP & RAP ===
	"hip-hop",
	"hip hop",
	"hiphop",
	"rap",
	"gangsta rap",
	"underground hip-hop",
	"underground hip hop",
	"instrumental hip-hop",
	"rapcore",
	"drill",
	"uk drill",
	"boom bap",
	"lo-fi hip hop",
	"cloud rap",
	"conscious hip-hop",
	"alternative hip-hop",
	"east coast hip-hop",
	"west coast hip-hop",
	"southern hip-hop",
	"dirty south",
	"crunk",
	"emo rap",
	"midwest rap",
	"southern rap",
	"trap rap",
	"afro trap",

	// === R&B & SOUL ===
	"rnb",
	"r&b",
	"soul",
	"neo-soul",
	"neo soul",
	"motown",
	"funk",
	"funky",
	"rhythm and blues",
	"gospel",
	"southern soul",
	"deep soul",
	"northern soul",
	"quiet storm",
	"new jack swing",
	"contemporary r&b",
	"alternative r&b",
	"psychedelic soul",
	"psychedelic funk",
	"contemporary soul",
	"p-funk",
	"funk rock",
	"hip hop soul",

	// === POP ===
	"pop",
	"indie pop",
	"synth-pop",
	"art pop",
	"chamber pop",
	"baroque pop",
	"jangle pop",
	"dance-pop",
	"europop",
	"k-pop",
	"kpop",
	"j-pop",
	"jpop",
	"c-pop",
	"latin pop",
	"hyperpop",
	"teen pop",
	"vocal pop",
	"folk pop",
	"folk-pop",
	"country pop",
	"country-pop",
	"sophisti-pop",
	"doo wop",
	"brill building sound",
	"emo pop",
	"emo-pop",
	"garage pop",
	"dance pop",

	// === JAZZ ===
	"jazz",
	"smooth jazz",
	"jazz fusion",
	"fusion",
	"bebop",
	"hard bop",
	"cool jazz",
	"free jazz",
	"avant-garde jazz",
	"modal jazz",
	"latin jazz",
	"nu jazz",
	"nu-jazz",
	"jazz rap",
	"swing",
	"big band",
	"contemporary jazz",
	"vocal jazz",
	"jazz vocal",
	"jazz piano",
	"dixieland",
	"ragtime",
	"gypsy jazz",
	"gypsy-jazz",
	"post-bop",
	"third stream",
	"jazz-funk",
	"jazz-rock",
	"future jazz",
	"jazz-blues",

	// === BLUES ===
	"blues",
	"electric blues",
	"delta blues",
	"chicago blues",
	"texas blues",
	"country blues",
	"contemporary blues",
	"psychedelic blues",
	"hill country blues",

	// === FOLK & COUNTRY ===
	"folk",
	"indie folk",
	"freak folk",
	"contemporary folk",
	"traditional folk",
	"traditional",
	"americana",
	"country",
	"alt-country",
	"outlaw country",
	"bluegrass",
	"newgrass",
	"old-time",
	"celtic",
	"irish folk",
	"scottish folk",
	"neofolk",
	"dark folk",
	"world",
	"world music",
	"progressive folk",
	"folk punk",
	"folk-punk",
	"pagan folk",
	"folk-jazz",
	"honky tonk",
	"hillbilly",
	"country boogie",
	"traditional country",

	// === CLASSICAL & ORCHESTRAL ===
	"classical",
	"baroque",
	"romantic",
	"contemporary classical",
	"modern classical",
	"minimalism",
	"neoclassical",
	"orchestral",
	"opera",
	"choral",
	"chamber music",
	"soundtrack",
	"ost",
	"score",
	"film score",
	"video game music",
	"medieval",

	// === REGGAE & CARIBBEAN ===
	"reggae",
	"ska",
	"ska punk",
	"rocksteady",
	"roots reggae",
	"lovers rock",
	"ragga",
	"soca",
	"calypso",

	// === LATIN ===
	"latin",
	"salsa",
	"bachata",
	"merengue",
	"reggaeton",
	"latin trap",
	"bossa nova",
	"samba",
	"mpb",
	"tropicalia",
	"cumbia",
	"tango",
	"flamenco",
	"mariachi",
	"norteno",
	"banda",
	"tejano",
	"corrido",
	"corrido tumbado",
	"dembow",
	"neoperreo",
	"ranchera",
	"mambo",
	"bolero",
	"afro-cuban",
	"latin folk",
	"flamenco pop",

	// === ASIAN ===
	"j-rock",
	"jrock",
	"city pop",
	"shibuya-kei",
	"anime",
	"anisong",
	"visual kei",
	"asian pop",
	"mandopop",
	"kayokyoku",
	"k-indie",
	"j-indie",

	// === MIDDLE EASTERN & AFRICAN ===
	"arabic",
	"afrobeat",
	"afrobeats",
	"highlife",
	"afropop",
	"ethio-jazz",
	"desert blues",
	"gnawa",
	"rai",
	"ethnic",
	"kuduro",
	"semba",
	"griot",
	"afro-rock",

	// === OTHER GENRES ===
	"singer-songwriter",
	"singer songwriter",
	"acoustic",
	"instrumental",
	"experimental",
	"avant-garde",
	"avantgarde",
	"lo-fi",
	"lofi",
	"easy listening",
	"dreamy",
	"ethereal",
	"atmospheric",
	"twee",
	"spoken word",
	"poetry",
	"comedy",
	"funny",
	"musical",
	"disney",
	"christmas",
	"christian",
	"christian rock",
	"worship",
	"spiritual",
	"darkwave",
	"coldwave",
	"ethereal wave",
	"power electronics",
	"martial industrial",
	"harsh noise",
	"urban",
	"crossover",
	"mashup",
	"groovy",
	"ballad",
	"oldies",
	"chanson",
	"chanson francaise",
	"schlager",
	"vocal",
	"fado",
	"polka",
	"industrial folk",
	"ambient folk",
	"folk noir",
]);

/**
 * Maps variant spellings to a single canonical form.
 * Canonical form is the key; variants are listed as values.
 */
const CANONICAL_GROUPS: Record<string, string[]> = {
	"hip-hop": ["hip hop", "hiphop"],
	"k-pop": ["kpop", "k pop"],
	"j-pop": ["jpop", "j pop"],
	"j-rock": ["jrock", "j rock"],
	rnb: ["r&b", "rhythm and blues"],
	"trip-hop": ["trip hop"],
	"lo-fi": ["lofi", "lo fi"],
	"post-punk": ["post punk"],
	"post-rock": ["post rock"],
	"post-hardcore": ["post hardcore"],
	synthpop: ["synth pop", "synth-pop"],
	"folk rock": ["folk-rock"],
	"pop rock": ["pop-rock"],
	"nu-metal": ["nu metal"],
	"singer-songwriter": ["singer songwriter"],
	"neo-soul": ["neo soul"],
	"drum and bass": ["drum n bass", "dnb"],
	"alternative rock": ["alt rock"],
	"avant-garde": ["avantgarde"],
	chillout: ["chill out"],
	"nu-jazz": ["nu jazz"],
	"underground hip-hop": ["underground hip hop"],
	"lo-fi hip-hop": ["lo-fi hip hop"],
	"power pop": ["powerpop"],
	"hard-techno": ["hard techno", "hardtechno"],
	"dance-pop": ["dance pop"],
	"gypsy jazz": ["gypsy-jazz"],
	"folk pop": ["folk-pop"],
	"folk punk": ["folk-punk"],
	"emo pop": ["emo-pop"],
	"country pop": ["country-pop"],
};

const CANON_MAP: ReadonlyMap<string, string> = new Map(
	Object.entries(CANONICAL_GROUPS).flatMap(([canonical, variants]) =>
		variants.map((v) => [v, canonical] as const),
	),
);

/**
 * Check if a tag is a recognized genre.
 * Performs case-insensitive lookup against the whitelist.
 */
export function isGenre(tag: string): boolean {
	return GENRE_WHITELIST.has(tag.toLowerCase());
}

/**
 * Canonicalize a genre tag to its preferred spelling.
 * Returns the canonical form (lowercase, hyphenated where appropriate).
 */
export function canonicalizeGenre(tag: string): string {
	const lower = tag.toLowerCase();
	return CANON_MAP.get(lower) ?? lower;
}

/**
 * Flat array of every entry in the whitelist, for client-side filtering UIs.
 * The whitelist intentionally contains both canonical forms and their variants
 * (e.g. "hip-hop" AND "hip hop", "rnb" AND "r&b") — Phase 2 UI should dedupe
 * these via canonicalizeGenre before display.
 */
export const GENRE_LIST: readonly string[] = Array.from(GENRE_WHITELIST);

/**
 * Sanitize user-supplied genre pills before persistence.
 * Order: trim whitespace → canonicalize variants → filter to whitelist →
 * deduplicate → cap at 5. Canonicalize runs before membership check so
 * variants (e.g. "hip hop") map to their canonical form ("hip-hop") and
 * still pass the whitelist filter.
 */
export function sanitizeGenrePills(input: string[]): string[] {
	const seen = new Set<string>();
	const result: string[] = [];
	for (const raw of input) {
		const trimmed = raw.trim();
		if (!trimmed) continue;
		const canonical = canonicalizeGenre(trimmed);
		if (!isGenre(canonical)) continue;
		if (seen.has(canonical)) continue;
		seen.add(canonical);
		result.push(canonical);
		if (result.length === 5) break;
	}
	return result;
}
