import type { SongDetail } from "@/features/liked-songs/components/song-detail-panel/song-detail-types";
import {
	type SongRead,
	SongReadSchema,
} from "@/lib/domains/enrichment/content-analysis/read-schema";
import { DEFAULT_THEME } from "@/lib/theme/types";

export interface LandingSongManifest {
	id: number;
	spotifyTrackId: string;
	name: string;
	artist: string;
	album: string;
	albumArtUrl: string;
	artistImageUrl?: string;
	spotifyArtistId: string;
	genres: string[];
	detailPath: string;
}

interface LandingSongAudioFeatures {
	tempo: number | null;
	energy: number | null;
	valence: number | null;
}

export interface LandingSongDetail
	extends Omit<LandingSongManifest, "detailPath"> {
	genres: string[];
	audioFeatures: LandingSongAudioFeatures;
	// The v17 { read } model (SongRead), generated by scripts/landing/regenerate-read.ts.
	// Nullable so a stub or a not-yet-regenerated fixture degrades to the "in progress" state
	// rather than crashing the hero.
	read: SongRead | null;
}

export type LandingSongForUI = LandingSongManifest | LandingSongDetail;

function isLandingSongDetail(
	song: LandingSongForUI,
): song is LandingSongDetail {
	return "read" in song;
}

// Validate at the edge: the fixture is generated against SongReadSchema, but re-parsing here
// means a hand-edited or stale file falls back to null instead of rendering a malformed read.
export function getLandingRead(song: LandingSongForUI): SongRead | null {
	if (!isLandingSongDetail(song) || !song.read) return null;
	const parsed = SongReadSchema.safeParse(song.read);
	return parsed.success ? parsed.data : null;
}

// Build the SongDetail the production SongDetailPanelSurface consumes straight from a
// landing fixture — the landing renders the same panel as the app, so it needs the same
// shape. Art overrides let the hero pass the manifest's image URLs (which it already
// resolves) rather than re-reading them off the song.
export function landingSongToSongDetail(
	song: LandingSongForUI,
	overrides?: { albumArtUrl?: string; artistImageUrl?: string },
): SongDetail {
	const detail = isLandingSongDetail(song) ? song : null;
	return {
		id: song.spotifyTrackId,
		spotifyTrackId: song.spotifyTrackId,
		title: song.name,
		artist: song.artist,
		album: song.album,
		genres: song.genres ?? [],
		audioFeatures: detail?.audioFeatures ?? {
			tempo: null,
			energy: null,
			valence: null,
		},
		theme: DEFAULT_THEME,
		albumArtUrl: overrides?.albumArtUrl ?? song.albumArtUrl,
		artistImageUrl: overrides?.artistImageUrl ?? song.artistImageUrl,
		displayState: detail ? "analyzed" : "pending",
		read: getLandingRead(song),
		instrumentalRead: null,
	};
}

function resolveAssetPath(path: string): string {
	const baseUrl = import.meta.env.BASE_URL ?? "/";
	const normalizedBase = baseUrl.endsWith("/") ? baseUrl : `${baseUrl}/`;
	const normalizedPath = path.startsWith("/") ? path.slice(1) : path;
	return `${normalizedBase}${normalizedPath}`;
}

async function fetchJson<T>(path: string): Promise<T> {
	const response = await fetch(resolveAssetPath(path), { cache: "default" });
	if (!response.ok) {
		throw new Error(`Failed to fetch ${path}: ${response.status}`);
	}
	return (await response.json()) as T;
}

export async function loadLandingSongDetail(
	detailPath: string,
): Promise<LandingSongDetail> {
	return fetchJson<LandingSongDetail>(detailPath);
}
