/**
 * Metric Registry and Governance Contract for Hearted Telemetry.
 *
 * Defines canonical metric definitions, sources of truth, exact numerator/denominator,
 * UTC range semantics, known limitations, and launch boundaries.
 */

// The earliest production account was created on this UTC date, so day-level
// launch reporting begins at its midnight boundary.
export const LAUNCH_DATE = "2026-06-12T00:00:00.000Z" as const;
export const ACTIVITY_HISTORY_MIGRATION_DATE =
	"2026-08-16T18:00:00.000Z" as const;
export const ACTIVITY_HISTORY_COMPLETE_FROM =
	"2026-08-17T00:00:00.000Z" as const;

export const SUPPORTED_TELEMETRY_PRESETS = [
	"24h",
	"7d",
	"14d",
	"30d",
	"90d",
	"launch",
] as const;

export type TelemetryPreset = (typeof SUPPORTED_TELEMETRY_PRESETS)[number];

export interface MetricDefinition {
	id: string;
	name: string;
	numerator: string;
	denominator: string | null;
	canonicalSource: string;
	timestampColumn: string | null;
	inclusionRules: string;
	utcSemantics: string;
	limitations: string;
	corroboratingEvent: string | null;
}

export const METRIC_REGISTRY: Record<string, MetricDefinition> = {
	// --- Funnel Cohort Metrics ---
	funnel_account_created: {
		id: "funnel_account_created",
		name: "Account Created",
		numerator: "Distinct accounts with created_at in cohort range",
		denominator: null,
		canonicalSource: "Supabase account.created_at",
		timestampColumn: "created_at",
		inclusionRules: "account.created_at >= from AND account.created_at < to",
		utcSemantics: "UTC half-open [from, to)",
		limitations: "None",
		corroboratingEvent: "signup_succeeded",
	},
	funnel_spotify_connected: {
		id: "funnel_spotify_connected",
		name: "Spotify Connected",
		numerator: "Cohort accounts where spotify_id IS NOT NULL",
		denominator: "funnel_account_created",
		canonicalSource: "Supabase account.spotify_id",
		timestampColumn: null,
		inclusionRules: "Cohort accounts where spotify_id is currently populated",
		utcSemantics: "Eventual state within signup cohort",
		limitations:
			"Eventual state only; Spotify connection has no dedicated historical milestone timestamp today. No fake timestamp is derived.",
		corroboratingEvent: null,
	},
	funnel_library_synced: {
		id: "funnel_library_synced",
		name: "Library Synced",
		numerator:
			"Cohort accounts with a completed extension_sync job",
		denominator: "funnel_account_created",
		canonicalSource: "Supabase job (type = 'extension_sync', status = 'completed')",
		timestampColumn: "completed_at",
		inclusionRules: "First completed extension_sync job per account",
		utcSemantics: "UTC half-open [from, to)",
		limitations: "Covers extension-driven library synchronizations",
		corroboratingEvent: null,
	},
	funnel_onboarding_completed: {
		id: "funnel_onboarding_completed",
		name: "Onboarding Completed",
		numerator:
			"Cohort accounts with user_preferences.onboarding_completed_at IS NOT NULL",
		denominator: "funnel_account_created",
		canonicalSource: "Supabase user_preferences.onboarding_completed_at",
		timestampColumn: "onboarding_completed_at",
		inclusionRules: "Cohort accounts that finished onboarding wizard",
		utcSemantics: "UTC half-open [from, to)",
		limitations: "None",
		corroboratingEvent: "onboarding_completed",
	},
	funnel_matches_available: {
		id: "funnel_matches_available",
		name: "Matches Available",
		numerator: "Cohort accounts with at least one match_snapshot row",
		denominator: "funnel_account_created",
		canonicalSource: "Supabase match_snapshot.created_at",
		timestampColumn: "created_at",
		inclusionRules: "First match_snapshot created for account",
		utcSemantics: "UTC half-open [from, to)",
		limitations: "Produced by matching pipeline after enrichment",
		corroboratingEvent: "match_snapshot_published",
	},
	funnel_match_engaged: {
		id: "funnel_match_engaged",
		name: "Match Engaged",
		numerator: "Cohort accounts with at least one match_event row",
		denominator: "funnel_account_created",
		canonicalSource: "Supabase match_event.occurred_at",
		timestampColumn: "occurred_at",
		inclusionRules: "First match_event (added/dismissed/skipped) for account",
		utcSemantics: "UTC half-open [from, to)",
		limitations: "Queue review deck interactions only",
		corroboratingEvent: "match_deck_action",
	},
	funnel_first_value: {
		id: "funnel_first_value",
		name: "First Value (Song Added)",
		numerator: "Cohort accounts with at least one match_event.event = 'added'",
		denominator: "funnel_account_created",
		canonicalSource: "Supabase match_event.occurred_at",
		timestampColumn: "occurred_at",
		inclusionRules: "First 'added' decision event for account",
		utcSemantics: "UTC half-open [from, to)",
		limitations: "North star product activation milestone",
		corroboratingEvent: "song_added_to_playlist",
	},
	funnel_paid: {
		id: "funnel_paid",
		name: "Paid Activation",
		numerator: "Cohort accounts with at least one billing_activation row",
		denominator: "funnel_account_created",
		canonicalSource: "Supabase billing_activation.created_at",
		timestampColumn: "created_at",
		inclusionRules: "First billing_activation recorded for account",
		utcSemantics: "UTC half-open [from, to)",
		limitations: "Tracks paid subscription activations",
		corroboratingEvent: "purchase_confirmed (legacy)",
	},

	funnel_conversion_rates: {
		id: "funnel_conversion_rates",
		name: "Funnel Conversion Rates",
		numerator: "Accounts reaching the current milestone",
		denominator: "Signup accounts or accounts reaching the previous milestone",
		canonicalSource: "Derived from canonical Supabase funnel stage counts",
		timestampColumn: null,
		inclusionRules: "Withheld when the signup cohort contains fewer than 10 accounts",
		utcSemantics: "Inputs use the cohort's UTC half-open [from, to) range",
		limitations: "Spotify connection is eventual state rather than a timed milestone",
		corroboratingEvent: null,
	},
	funnel_milestone_timing: {
		id: "funnel_milestone_timing",
		name: "Funnel Milestone Timing",
		numerator: "Median and p75 seconds from account creation to each milestone",
		denominator: null,
		canonicalSource: "Canonical Supabase milestone timestamps",
		timestampColumn: "created_at and each milestone timestamp",
		inclusionRules: "Non-negative durations for cohort accounts reaching the milestone",
		utcSemantics: "Absolute UTC timestamp differences",
		limitations: "Unavailable for Spotify connection because no historical timestamp exists",
		corroboratingEvent: null,
	},
	funnel_stuck_accounts: {
		id: "funnel_stuck_accounts",
		name: "Accounts Stuck at Funnel Stage",
		numerator: "Accounts in the current stage set but not the next stage set",
		denominator: null,
		canonicalSource: "Derived from canonical Supabase funnel milestones",
		timestampColumn: null,
		inclusionRules: "Set difference within the selected signup cohort",
		utcSemantics: "Inputs use the cohort's UTC half-open [from, to) range",
		limitations: "Later milestones can occur out of order, so stage sets need not be monotonic",
		corroboratingEvent: null,
	},

	// --- Activity Metrics ---
	activity_dau: {
		id: "activity_dau",
		name: "Daily Active Accounts (DAU)",
		numerator: "Distinct accounts with heartbeat recorded in account_activity_day",
		denominator: null,
		canonicalSource: "Supabase account_activity_day.activity_date",
		timestampColumn: "activity_date",
		inclusionRules: "Authenticated account presence per UTC calendar day",
		utcSemantics: "UTC date equality",
		limitations:
			"Dates before 2026-08-17 are unavailable because instrumentation began partway through 2026-08-16; the current UTC day is also incomplete.",
		corroboratingEvent: null,
	},
	activity_24h: {
		id: "activity_24h",
		name: "Current 24-Hour Active Accounts",
		numerator: "Distinct accounts with account_activity.last_seen_at >= now() - 24 hours",
		denominator: null,
		canonicalSource: "Supabase account_activity.last_seen_at",
		timestampColumn: "last_seen_at",
		inclusionRules: "Rolling 24-hour exact heartbeat window",
		utcSemantics: "UTC half-open [now - 24h, now)",
		limitations: "Current rolling window from latest heartbeat",
		corroboratingEvent: null,
	},
	activity_wau: {
		id: "activity_wau",
		name: "Current 7-Day Active Accounts (WAU)",
		numerator: "Distinct accounts with account_activity.last_seen_at >= now() - 7 days",
		denominator: null,
		canonicalSource: "Supabase account_activity.last_seen_at",
		timestampColumn: "last_seen_at",
		inclusionRules: "Rolling 7-day exact heartbeat window",
		utcSemantics: "UTC half-open [now - 7d, now)",
		limitations: "Current rolling window from latest heartbeat",
		corroboratingEvent: null,
	},
	activity_mau: {
		id: "activity_mau",
		name: "Current 30-Day Active Accounts (MAU)",
		numerator: "Distinct accounts with account_activity.last_seen_at >= now() - 30 days",
		denominator: null,
		canonicalSource: "Supabase account_activity.last_seen_at",
		timestampColumn: "last_seen_at",
		inclusionRules: "Rolling 30-day exact heartbeat window",
		utcSemantics: "UTC half-open [now - 30d, now)",
		limitations: "Current rolling window from latest heartbeat",
		corroboratingEvent: null,
	},
	activity_observed_visitors: {
		id: "activity_observed_visitors",
		name: "Observed Web Visitors",
		numerator: "Distinct distinct_id values in PostHog events",
		denominator: null,
		canonicalSource: "PostHog events ($pageview, interaction)",
		timestampColumn: "timestamp",
		inclusionRules: "All observed browser events in selected range",
		utcSemantics: "UTC half-open [from, to)",
		limitations:
			"Subject to privacy consent, ad-blockers, and network loss; never overrides DB facts.",
		corroboratingEvent: null,
	},

	// --- Engagement Metrics ---
	engagement_sessions_started: {
		id: "engagement_sessions_started",
		name: "Match Sessions Started",
		numerator: "Total match_review_session rows created in range",
		denominator: null,
		canonicalSource: "Supabase match_review_session.created_at",
		timestampColumn: "created_at",
		inclusionRules: "created_at >= from AND created_at < to",
		utcSemantics: "UTC half-open [from, to)",
		limitations: "Queue review deck sessions",
		corroboratingEvent: null,
	},
	engagement_sessions_completed: {
		id: "engagement_sessions_completed",
		name: "Match Sessions Completed",
		numerator:
			"Total match_review_session rows with status = 'completed' in range",
		denominator: null,
		canonicalSource: "Supabase match_review_session.completed_at",
		timestampColumn: "completed_at",
		inclusionRules:
			"status = 'completed' AND completed_at >= from AND completed_at < to",
		utcSemantics: "UTC half-open [from, to)",
		limitations: "None",
		corroboratingEvent: null,
	},
	engagement_suggestions_served: {
		id: "engagement_suggestions_served",
		name: "Match Suggestions Served",
		numerator: "Total captured visible suggestion pairs in range",
		denominator: null,
		canonicalSource: "Supabase match_review_item_visible_pair.captured_at",
		timestampColumn: "captured_at",
		inclusionRules: "captured_at >= from AND captured_at < to",
		utcSemantics: "UTC half-open [from, to)",
		limitations:
			"Counts every suggestion in the captured list, including presentations later abandoned without a decision.",
		corroboratingEvent: null,
	},
	engagement_explicit_add_rate: {
		id: "engagement_explicit_add_rate",
		name: "Explicit-Decision Add Rate",
		numerator: "count(match_event WHERE event = 'added')",
		denominator: "count(match_event WHERE event IN ('added', 'dismissed'))",
		canonicalSource: "Supabase match_event",
		timestampColumn: "occurred_at",
		inclusionRules: "Explicit decisions only; excludes skips",
		utcSemantics: "UTC half-open [from, to)",
		limitations: "Excludes skips by design",
		corroboratingEvent: null,
	},
	engagement_served_add_rate: {
		id: "engagement_served_add_rate",
		name: "Served-Item Add Rate",
		numerator: "count(match_event WHERE event = 'added')",
		denominator: "engagement_suggestions_served",
		canonicalSource:
			"Supabase match_event joined conceptually to match_review_item_visible_pair presentations",
		timestampColumn: "occurred_at / captured_at",
		inclusionRules:
			"Added outcomes divided by all visible suggestion pairs captured in the range",
		utcSemantics: "UTC half-open [from, to)",
		limitations: "None",
		corroboratingEvent: null,
	},

	// --- Economics Metrics ---
	economics_llm_spend: {
		id: "economics_llm_spend",
		name: "Total LLM Spend",
		numerator: "Sum of cost_usd in llm_usage table",
		denominator: null,
		canonicalSource: "Supabase llm_usage.cost_usd",
		timestampColumn: "created_at",
		inclusionRules: "created_at >= from AND created_at < to",
		utcSemantics: "UTC half-open [from, to)",
		limitations:
			"Token × list-price estimate; unpriced models record NULL cost_usd.",
		corroboratingEvent: null,
	},

	// --- Retention and observed traffic ---
	activity_week1_retention: {
		id: "activity_week1_retention",
		name: "Week 1 Signup Retention",
		numerator: "Cohort accounts active during days 7 through 13 after signup",
		denominator: "Accounts in the UTC signup-week cohort",
		canonicalSource: "Supabase account joined to account_activity_day",
		timestampColumn: "account.created_at / account_activity_day.activity_date",
		inclusionRules:
			"Only mature cohorts whose full observation window begins on or after 2026-08-17",
		utcSemantics: "UTC signup weeks and UTC activity dates",
		limitations: "Unavailable for immature or pre-instrumentation cohorts",
		corroboratingEvent: null,
	},
	activity_week4_retention: {
		id: "activity_week4_retention",
		name: "Week 4 Signup Retention",
		numerator: "Cohort accounts active during days 28 through 34 after signup",
		denominator: "Accounts in the UTC signup-week cohort",
		canonicalSource: "Supabase account joined to account_activity_day",
		timestampColumn: "account.created_at / account_activity_day.activity_date",
		inclusionRules:
			"Only mature cohorts whose full observation window begins on or after 2026-08-17",
		utcSemantics: "UTC signup weeks and UTC activity dates",
		limitations: "Unavailable for immature or pre-instrumentation cohorts",
		corroboratingEvent: null,
	},
	activity_observed_pageviews: {
		id: "activity_observed_pageviews",
		name: "Observed Pageviews",
		numerator: "Count of PostHog $pageview events",
		denominator: null,
		canonicalSource: "PostHog events",
		timestampColumn: "timestamp",
		inclusionRules: "event = '$pageview'",
		utcSemantics: "UTC half-open [from, to)",
		limitations: "Subject to consent, blocking, and delivery loss",
		corroboratingEvent: null,
	},
	activity_observed_sessions: {
		id: "activity_observed_sessions",
		name: "Observed Sessions",
		numerator: "Distinct PostHog properties.$session_id values",
		denominator: null,
		canonicalSource: "PostHog events",
		timestampColumn: "timestamp",
		inclusionRules: "All events with a session identifier in range",
		utcSemantics: "UTC half-open [from, to)",
		limitations: "Subject to consent, blocking, and delivery loss",
		corroboratingEvent: null,
	},
	activity_observed_routes: {
		id: "activity_observed_routes",
		name: "Observed Route Views",
		numerator: "Count of $pageview events grouped by pathname",
		denominator: null,
		canonicalSource: "PostHog events properties.$pathname / $current_url",
		timestampColumn: "timestamp",
		inclusionRules: "Top 50 routes; missing paths are grouped as unknown",
		utcSemantics: "UTC half-open [from, to)",
		limitations: "Subject to consent, blocking, and delivery loss",
		corroboratingEvent: null,
	},

	// --- Remaining engagement outputs ---
	engagement_added: {
		id: "engagement_added",
		name: "Songs Added",
		numerator: "Count of match_event rows where event = 'added'",
		denominator: null,
		canonicalSource: "Supabase match_event",
		timestampColumn: "occurred_at",
		inclusionRules: "occurred_at >= from AND occurred_at < to",
		utcSemantics: "UTC half-open [from, to)",
		limitations: "Queue review interactions only",
		corroboratingEvent: "match_deck_action",
	},
	engagement_dismissed: {
		id: "engagement_dismissed",
		name: "Songs Dismissed",
		numerator: "Count of match_event rows where event = 'dismissed'",
		denominator: null,
		canonicalSource: "Supabase match_event",
		timestampColumn: "occurred_at",
		inclusionRules: "occurred_at >= from AND occurred_at < to",
		utcSemantics: "UTC half-open [from, to)",
		limitations: "Queue review interactions only",
		corroboratingEvent: "match_deck_action",
	},
	engagement_skipped: {
		id: "engagement_skipped",
		name: "Songs Skipped",
		numerator: "Count of match_event rows where event = 'skipped'",
		denominator: null,
		canonicalSource: "Supabase match_event",
		timestampColumn: "occurred_at",
		inclusionRules: "occurred_at >= from AND occurred_at < to",
		utcSemantics: "UTC half-open [from, to)",
		limitations: "Queue review interactions only",
		corroboratingEvent: "match_deck_action",
	},
	engagement_total_decisions: {
		id: "engagement_total_decisions",
		name: "Total Explicit Decisions",
		numerator: "Added match events plus dismissed match events",
		denominator: null,
		canonicalSource: "Supabase match_event",
		timestampColumn: "occurred_at",
		inclusionRules: "Excludes skipped outcomes",
		utcSemantics: "UTC half-open [from, to)",
		limitations: "Queue review interactions only",
		corroboratingEvent: "match_deck_action",
	},
	engagement_accounts: {
		id: "engagement_accounts",
		name: "Engaged Matching Accounts",
		numerator: "Distinct match_event.account_id values",
		denominator: null,
		canonicalSource: "Supabase match_event",
		timestampColumn: "occurred_at",
		inclusionRules: "Any added, dismissed, or skipped event in range",
		utcSemantics: "UTC half-open [from, to)",
		limitations: "Queue review interactions only",
		corroboratingEvent: null,
	},
	engagement_match_sessions: {
		id: "engagement_match_sessions",
		name: "Sessions With Outcomes",
		numerator: "Distinct non-null match_event.session_id values",
		denominator: null,
		canonicalSource: "Supabase match_event",
		timestampColumn: "occurred_at",
		inclusionRules: "Any persisted match outcome in range",
		utcSemantics: "UTC half-open [from, to)",
		limitations: "May be lower than sessions started because abandonment is retained",
		corroboratingEvent: null,
	},
	engagement_decisions_per_account: {
		id: "engagement_decisions_per_account",
		name: "Explicit Decisions per Engaged Account",
		numerator: "engagement_total_decisions",
		denominator: "engagement_accounts",
		canonicalSource: "Supabase match_event",
		timestampColumn: "occurred_at",
		inclusionRules: "Null when no account engaged",
		utcSemantics: "UTC half-open [from, to)",
		limitations: "Queue review interactions only",
		corroboratingEvent: null,
	},
	engagement_orientation_split: {
		id: "engagement_orientation_split",
		name: "Outcome Orientation Split",
		numerator: "Match events grouped by served_orientation",
		denominator: null,
		canonicalSource: "Supabase match_event.served_orientation",
		timestampColumn: "occurred_at",
		inclusionRules: "Legacy null orientation is grouped with song orientation",
		utcSemantics: "UTC half-open [from, to)",
		limitations: "Null legacy values cannot be reconstructed",
		corroboratingEvent: null,
	},
	engagement_time_to_first_decision: {
		id: "engagement_time_to_first_decision",
		name: "Median Time to First Decision",
		numerator: "Median seconds from first match snapshot to first match event",
		denominator: null,
		canonicalSource: "Supabase match_snapshot and match_event",
		timestampColumn: "created_at / occurred_at",
		inclusionRules: "Signup cohort accounts with ordered snapshot and decision timestamps",
		utcSemantics: "Signup cohort uses UTC half-open [from, to)",
		limitations: "Cohort metric, not an event-range metric",
		corroboratingEvent: null,
	},
	engagement_time_to_first_add: {
		id: "engagement_time_to_first_add",
		name: "Median Time from First Decision to First Add",
		numerator: "Median seconds from first match event to first added event",
		denominator: null,
		canonicalSource: "Supabase match_event",
		timestampColumn: "occurred_at",
		inclusionRules: "Signup cohort accounts with a first add after first decision",
		utcSemantics: "Signup cohort uses UTC half-open [from, to)",
		limitations: "Cohort metric, not an event-range metric",
		corroboratingEvent: null,
	},

	// --- Remaining economics outputs ---
	economics_spend_comparison: {
		id: "economics_spend_comparison",
		name: "LLM Spend Period Comparison",
		numerator: "Current-period LLM spend minus previous-period LLM spend",
		denominator: "Previous-period LLM spend for percentage delta",
		canonicalSource: "Supabase llm_usage.cost_usd",
		timestampColumn: "created_at",
		inclusionRules: "Adjacent equal-duration periods; percentage is null when prior spend is zero",
		utcSemantics: "Two adjacent UTC half-open ranges",
		limitations: "Token × list-price estimate rather than invoiced spend",
		corroboratingEvent: null,
	},
	economics_llm_calls: {
		id: "economics_llm_calls",
		name: "LLM Calls",
		numerator: "Count of llm_usage rows",
		denominator: null,
		canonicalSource: "Supabase llm_usage",
		timestampColumn: "created_at",
		inclusionRules: "All recorded call sites in range",
		utcSemantics: "UTC half-open [from, to)",
		limitations: "Missing ledger writes are not recoverable from this metric",
		corroboratingEvent: null,
	},
	economics_llm_tokens: {
		id: "economics_llm_tokens",
		name: "LLM Input and Output Tokens",
		numerator: "Sum of input_tokens and output_tokens, reported separately",
		denominator: null,
		canonicalSource: "Supabase llm_usage",
		timestampColumn: "created_at",
		inclusionRules: "All recorded call sites in range",
		utcSemantics: "UTC half-open [from, to)",
		limitations: "Provider-reported token accounting",
		corroboratingEvent: null,
	},
	economics_spend_breakdown: {
		id: "economics_spend_breakdown",
		name: "LLM Spend Breakdown",
		numerator: "Calls, tokens, and cost grouped by function, model, provider, or UTC day",
		denominator: null,
		canonicalSource: "Supabase llm_usage",
		timestampColumn: "created_at",
		inclusionRules: "All recorded call sites in range",
		utcSemantics: "UTC half-open [from, to); daily groups use UTC dates",
		limitations: "Unpriced models contribute calls and tokens but zero summed cost",
		corroboratingEvent: null,
	},
	economics_cost_per_song_analysis: {
		id: "economics_cost_per_song_analysis",
		name: "Cost per Song Analysis",
		numerator:
			"LLM cost for song-analysis, song-rewrite, and voice-audit-rewrite-pass calls",
		denominator: "Distinct song_analysis.song_id rows created in range",
		canonicalSource: "Supabase llm_usage and song_analysis",
		timestampColumn: "created_at",
		inclusionRules: "Numerator and denominator independently use the same range",
		utcSemantics: "UTC half-open [from, to)",
		limitations: "List-price estimate; null when no songs were analyzed",
		corroboratingEvent: null,
	},
	economics_cost_per_activated_account: {
		id: "economics_cost_per_activated_account",
		name: "Total LLM Cost per Activated Account",
		numerator: "economics_llm_spend",
		denominator: "Accounts completing onboarding in range",
		canonicalSource: "Supabase llm_usage and user_preferences",
		timestampColumn: "created_at / onboarding_completed_at",
		inclusionRules: "All LLM work divided by activations in the same range",
		utcSemantics: "UTC half-open [from, to)",
		limitations: "Blended business unit cost, not causal per-account attribution",
		corroboratingEvent: null,
	},
	economics_cost_per_paid_account: {
		id: "economics_cost_per_paid_account",
		name: "Total LLM Cost per Paid Account",
		numerator: "economics_llm_spend",
		denominator: "Distinct billing_activation.account_id values in range",
		canonicalSource: "Supabase llm_usage and billing_activation",
		timestampColumn: "created_at",
		inclusionRules: "All LLM work divided by paid accounts in the same range",
		utcSemantics: "UTC half-open [from, to)",
		limitations: "Blended business unit cost, not causal per-account attribution",
		corroboratingEvent: null,
	},
	economics_active_subscriptions: {
		id: "economics_active_subscriptions",
		name: "Current Active Subscriptions",
		numerator: "Count of account_billing rows with subscription_status = 'active'",
		denominator: null,
		canonicalSource: "Supabase account_billing",
		timestampColumn: null,
		inclusionRules: "Current state at query time",
		utcSemantics: "Point-in-time snapshot",
		limitations: "Not scoped to the selected historical range",
		corroboratingEvent: null,
	},
	economics_paid_activations: {
		id: "economics_paid_activations",
		name: "New Paid Activations",
		numerator: "Count of billing_activation rows",
		denominator: null,
		canonicalSource: "Supabase billing_activation",
		timestampColumn: "created_at",
		inclusionRules: "Current and previous periods are reported separately",
		utcSemantics: "UTC half-open [from, to)",
		limitations: "Activation records, not current subscription state",
		corroboratingEvent: "purchase_confirmed (legacy)",
	},

	// --- Coverage and freshness ---
	coverage_event_count: {
		id: "coverage_event_count",
		name: "Canonical/PostHog Event Count",
		numerator: "Event count from each named source for the same semantic milestone",
		denominator: null,
		canonicalSource:
			"Supabase canonical milestone tables and allowlisted PostHog events",
		timestampColumn: "Milestone timestamp / PostHog timestamp",
		inclusionRules: "Four allowlisted reconciliation milestones",
		utcSemantics: "UTC half-open [from, to)",
		limitations: "PostHog observations are non-canonical and may be missing",
		corroboratingEvent: null,
	},
	coverage_distinct_accounts: {
		id: "coverage_distinct_accounts",
		name: "Canonical/PostHog Distinct Accounts",
		numerator: "Distinct account identifiers observed for each reconciliation milestone",
		denominator: null,
		canonicalSource: "Supabase canonical facts and PostHog distinct_id",
		timestampColumn: "Milestone timestamp / PostHog timestamp",
		inclusionRules: "Four allowlisted reconciliation milestones",
		utcSemantics: "UTC half-open [from, to)",
		limitations: "PostHog distinct_id depends on correct client identification",
		corroboratingEvent: null,
	},
	coverage_percent: {
		id: "coverage_percent",
		name: "PostHog Event Coverage",
		numerator: "PostHog event count",
		denominator: "Canonical database fact count",
		canonicalSource: "Derived reconciliation metric",
		timestampColumn: null,
		inclusionRules: "Null when canonical count is zero; low-volume below 10 is flagged",
		utcSemantics: "Both inputs use the same UTC half-open range",
		limitations: "Semantic mismatches can produce values above 100%",
		corroboratingEvent: null,
	},
	source_freshness: {
		id: "source_freshness",
		name: "Source Freshness",
		numerator: "Latest canonical DB timestamp and latest PostHog event timestamp",
		denominator: null,
		canonicalSource: "Supabase health query and PostHog max(timestamp)",
		timestampColumn: "Latest available source timestamp",
		inclusionRules: "Point-in-time source health check",
		utcSemantics: "UTC timestamps",
		limitations: "Latest DB activity combines account, heartbeat, and match activity",
		corroboratingEvent: null,
	},
};
