/**
 * Syncs the subset of LiteLLM's price catalogue we actually bill against into a
 * pinned, vendored JSON the runtime reads (src/lib/integrations/llm/model-prices.generated.json).
 *
 * Why vendored: prod must have NO network dependency and deterministic, testable
 * pricing. LiteLLM's model_prices_and_context_window.json is the free,
 * community-maintained "regularly updated" source; we snapshot only the models we
 * use plus a _synced_at stamp (which becomes each ledger row's price_version) so a
 * key miss or upstream outage can never make a live analysis fail.
 *
 * Run: `bun run scripts/sync-model-prices.ts`. Refresh on a schedule / in CI; the
 * cadence of this script is the only accuracy knob on the cost estimate.
 */

const SOURCE_URL =
	"https://raw.githubusercontent.com/BerriAI/litellm/main/model_prices_and_context_window.json";

const OUTPUT_PATH = new URL(
	"../src/lib/integrations/llm/model-prices.generated.json",
	import.meta.url,
);

// Bare model ids we call in production. Add an entry here when a new model goes live.
const MODELS_WE_USE = ["gemini-2.5-flash", "gemini-2.5-flash-lite"] as const;

// We bill through Vertex, so prefer the Vertex-priced entry. In LiteLLM the bare
// `gemini-2.5-flash` key IS the vertex_ai entry today and `gemini/<m>` is the
// AI-Studio one; list the explicit vertex prefix first anyway so we stay correct
// if upstream ever renames.
function candidateKeys(model: string): string[] {
	return [`vertex_ai/${model}`, model, `gemini/${model}`];
}

interface LiteLlmEntry {
	input_cost_per_token?: number;
	output_cost_per_token?: number;
	cache_read_input_token_cost?: number;
	litellm_provider?: string;
}

interface PinnedEntry {
	source_key: string;
	input_cost_per_token: number;
	output_cost_per_token: number;
	cache_read_input_token_cost: number | null;
}

async function main() {
	const res = await fetch(SOURCE_URL);
	if (!res.ok) {
		throw new Error(`Failed to fetch LiteLLM prices: ${res.status} ${res.statusText}`);
	}
	const catalogue = (await res.json()) as Record<string, LiteLlmEntry>;

	const models: Record<string, PinnedEntry> = {};
	const missing: string[] = [];

	for (const model of MODELS_WE_USE) {
		const sourceKey = candidateKeys(model).find((k) => {
			const e = catalogue[k];
			return (
				e &&
				typeof e.input_cost_per_token === "number" &&
				typeof e.output_cost_per_token === "number"
			);
		});
		if (!sourceKey) {
			missing.push(model);
			continue;
		}
		const e = catalogue[sourceKey];
		models[model] = {
			source_key: sourceKey,
			input_cost_per_token: e.input_cost_per_token as number,
			output_cost_per_token: e.output_cost_per_token as number,
			cache_read_input_token_cost:
				typeof e.cache_read_input_token_cost === "number"
					? e.cache_read_input_token_cost
					: null,
		};
		console.log(
			`✓ ${model} ← ${sourceKey}  in=${e.input_cost_per_token} out=${e.output_cost_per_token} cacheRead=${e.cache_read_input_token_cost ?? "—"}`,
		);
	}

	if (missing.length > 0) {
		// A model we bill against has no upstream price — fail loudly rather than
		// vendor a partial snapshot that would silently fall through to FALLBACK_PRICES.
		throw new Error(
			`No LiteLLM price found for: ${missing.join(", ")} (tried ${missing
				.map((m) => candidateKeys(m).join(" / "))
				.join("; ")})`,
		);
	}

	const output = {
		_comment:
			"Generated by scripts/sync-model-prices.ts — do not edit by hand. Costs are per-token (e.g. 3e-7 = $0.30/M).",
		_source: SOURCE_URL,
		_synced_at: new Date().toISOString(),
		models,
	};

	await Bun.write(OUTPUT_PATH, `${JSON.stringify(output, null, "\t")}\n`);
	console.log(`\nWrote ${Object.keys(models).length} models → ${OUTPUT_PATH.pathname}`);
}

main().catch((err) => {
	console.error(err instanceof Error ? err.message : String(err));
	process.exit(1);
});
