/**
 * Database types for Supabase.
 *
 * This file will be auto-generated by the Supabase CLI once schema migrations are in place.
 * Run: bunx supabase gen types typescript --project-id <project-id> > src/lib/data/database.types.ts
 *
 * For now, this provides a minimal stub to enable typed client usage.
 */
export type Database = {
	public: {
		Tables: Record<string, never>;
		Views: Record<string, never>;
		Functions: Record<string, never>;
		Enums: Record<string, never>;
		CompositeTypes: Record<string, never>;
	};
};
