/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HealthRouteImport } from './routes/health'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthLogoutRouteImport } from './routes/auth/logout'
import { Route as ApiSentryTunnelRouteImport } from './routes/api/sentry-tunnel'
import { Route as ApiBillingBridgeRouteImport } from './routes/api/billing-bridge'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedPlaylistsRouteImport } from './routes/_authenticated/playlists'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedMatchRouteImport } from './routes/_authenticated/match'
import { Route as AuthenticatedLikedSongsRouteImport } from './routes/_authenticated/liked-songs'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as ApiPosthogSplatRouteImport } from './routes/api/posthog/$'
import { Route as ApiExtensionTokenRouteImport } from './routes/api/extension/token'
import { Route as ApiExtensionSyncRouteImport } from './routes/api/extension/sync'
import { Route as ApiExtensionStatusRouteImport } from './routes/api/extension/status'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthenticatedPlaylistsPlaylistRefRouteImport } from './routes/_authenticated/playlists.$playlistRef'
import { Route as AuthenticatedCheckoutSuccessRouteImport } from './routes/_authenticated/checkout/success'
import { Route as AuthenticatedCheckoutCancelRouteImport } from './routes/_authenticated/checkout/cancel'
import { Route as ApiExtensionArtistsCheckRouteImport } from './routes/api/extension/artists/check'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLogoutRoute = AuthLogoutRouteImport.update({
  id: '/auth/logout',
  path: '/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSentryTunnelRoute = ApiSentryTunnelRouteImport.update({
  id: '/api/sentry-tunnel',
  path: '/api/sentry-tunnel',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBillingBridgeRoute = ApiBillingBridgeRouteImport.update({
  id: '/api/billing-bridge',
  path: '/api/billing-bridge',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlaylistsRoute = AuthenticatedPlaylistsRouteImport.update({
  id: '/playlists',
  path: '/playlists',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMatchRoute = AuthenticatedMatchRouteImport.update({
  id: '/match',
  path: '/match',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLikedSongsRoute = AuthenticatedLikedSongsRouteImport.update({
  id: '/liked-songs',
  path: '/liked-songs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPosthogSplatRoute = ApiPosthogSplatRouteImport.update({
  id: '/api/posthog/$',
  path: '/api/posthog/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExtensionTokenRoute = ApiExtensionTokenRouteImport.update({
  id: '/api/extension/token',
  path: '/api/extension/token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExtensionSyncRoute = ApiExtensionSyncRouteImport.update({
  id: '/api/extension/sync',
  path: '/api/extension/sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExtensionStatusRoute = ApiExtensionStatusRouteImport.update({
  id: '/api/extension/status',
  path: '/api/extension/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPlaylistsPlaylistRefRoute =
  AuthenticatedPlaylistsPlaylistRefRouteImport.update({
    id: '/$playlistRef',
    path: '/$playlistRef',
    getParentRoute: () => AuthenticatedPlaylistsRoute,
  } as any)
const AuthenticatedCheckoutSuccessRoute =
  AuthenticatedCheckoutSuccessRouteImport.update({
    id: '/checkout/success',
    path: '/checkout/success',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCheckoutCancelRoute =
  AuthenticatedCheckoutCancelRouteImport.update({
    id: '/checkout/cancel',
    path: '/checkout/cancel',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiExtensionArtistsCheckRoute =
  ApiExtensionArtistsCheckRouteImport.update({
    id: '/api/extension/artists/check',
    path: '/api/extension/artists/check',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/health': typeof HealthRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/liked-songs': typeof AuthenticatedLikedSongsRoute
  '/match': typeof AuthenticatedMatchRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/playlists': typeof AuthenticatedPlaylistsRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRoute
  '/api/billing-bridge': typeof ApiBillingBridgeRoute
  '/api/sentry-tunnel': typeof ApiSentryTunnelRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/checkout/cancel': typeof AuthenticatedCheckoutCancelRoute
  '/checkout/success': typeof AuthenticatedCheckoutSuccessRoute
  '/playlists/$playlistRef': typeof AuthenticatedPlaylistsPlaylistRefRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/extension/status': typeof ApiExtensionStatusRoute
  '/api/extension/sync': typeof ApiExtensionSyncRoute
  '/api/extension/token': typeof ApiExtensionTokenRoute
  '/api/posthog/$': typeof ApiPosthogSplatRoute
  '/api/extension/artists/check': typeof ApiExtensionArtistsCheckRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/health': typeof HealthRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/liked-songs': typeof AuthenticatedLikedSongsRoute
  '/match': typeof AuthenticatedMatchRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/playlists': typeof AuthenticatedPlaylistsRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRoute
  '/api/billing-bridge': typeof ApiBillingBridgeRoute
  '/api/sentry-tunnel': typeof ApiSentryTunnelRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/checkout/cancel': typeof AuthenticatedCheckoutCancelRoute
  '/checkout/success': typeof AuthenticatedCheckoutSuccessRoute
  '/playlists/$playlistRef': typeof AuthenticatedPlaylistsPlaylistRefRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/extension/status': typeof ApiExtensionStatusRoute
  '/api/extension/sync': typeof ApiExtensionSyncRoute
  '/api/extension/token': typeof ApiExtensionTokenRoute
  '/api/posthog/$': typeof ApiPosthogSplatRoute
  '/api/extension/artists/check': typeof ApiExtensionArtistsCheckRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/health': typeof HealthRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/liked-songs': typeof AuthenticatedLikedSongsRoute
  '/_authenticated/match': typeof AuthenticatedMatchRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/playlists': typeof AuthenticatedPlaylistsRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/api/billing-bridge': typeof ApiBillingBridgeRoute
  '/api/sentry-tunnel': typeof ApiSentryTunnelRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/_authenticated/checkout/cancel': typeof AuthenticatedCheckoutCancelRoute
  '/_authenticated/checkout/success': typeof AuthenticatedCheckoutSuccessRoute
  '/_authenticated/playlists/$playlistRef': typeof AuthenticatedPlaylistsPlaylistRefRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/extension/status': typeof ApiExtensionStatusRoute
  '/api/extension/sync': typeof ApiExtensionSyncRoute
  '/api/extension/token': typeof ApiExtensionTokenRoute
  '/api/posthog/$': typeof ApiPosthogSplatRoute
  '/api/extension/artists/check': typeof ApiExtensionArtistsCheckRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/faq'
    | '/forgot-password'
    | '/health'
    | '/login'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/verify-email'
    | '/dashboard'
    | '/liked-songs'
    | '/match'
    | '/onboarding'
    | '/playlists'
    | '/settings'
    | '/api/billing-bridge'
    | '/api/sentry-tunnel'
    | '/auth/logout'
    | '/checkout/cancel'
    | '/checkout/success'
    | '/playlists/$playlistRef'
    | '/api/auth/$'
    | '/api/extension/status'
    | '/api/extension/sync'
    | '/api/extension/token'
    | '/api/posthog/$'
    | '/api/extension/artists/check'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/faq'
    | '/forgot-password'
    | '/health'
    | '/login'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/verify-email'
    | '/dashboard'
    | '/liked-songs'
    | '/match'
    | '/onboarding'
    | '/playlists'
    | '/settings'
    | '/api/billing-bridge'
    | '/api/sentry-tunnel'
    | '/auth/logout'
    | '/checkout/cancel'
    | '/checkout/success'
    | '/playlists/$playlistRef'
    | '/api/auth/$'
    | '/api/extension/status'
    | '/api/extension/sync'
    | '/api/extension/token'
    | '/api/posthog/$'
    | '/api/extension/artists/check'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/faq'
    | '/forgot-password'
    | '/health'
    | '/login'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/verify-email'
    | '/_authenticated/dashboard'
    | '/_authenticated/liked-songs'
    | '/_authenticated/match'
    | '/_authenticated/onboarding'
    | '/_authenticated/playlists'
    | '/_authenticated/settings'
    | '/api/billing-bridge'
    | '/api/sentry-tunnel'
    | '/auth/logout'
    | '/_authenticated/checkout/cancel'
    | '/_authenticated/checkout/success'
    | '/_authenticated/playlists/$playlistRef'
    | '/api/auth/$'
    | '/api/extension/status'
    | '/api/extension/sync'
    | '/api/extension/token'
    | '/api/posthog/$'
    | '/api/extension/artists/check'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  FaqRoute: typeof FaqRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HealthRoute: typeof HealthRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TermsRoute: typeof TermsRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  ApiBillingBridgeRoute: typeof ApiBillingBridgeRoute
  ApiSentryTunnelRoute: typeof ApiSentryTunnelRoute
  AuthLogoutRoute: typeof AuthLogoutRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiExtensionStatusRoute: typeof ApiExtensionStatusRoute
  ApiExtensionSyncRoute: typeof ApiExtensionSyncRoute
  ApiExtensionTokenRoute: typeof ApiExtensionTokenRoute
  ApiPosthogSplatRoute: typeof ApiPosthogSplatRoute
  ApiExtensionArtistsCheckRoute: typeof ApiExtensionArtistsCheckRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/logout': {
      id: '/auth/logout'
      path: '/auth/logout'
      fullPath: '/auth/logout'
      preLoaderRoute: typeof AuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sentry-tunnel': {
      id: '/api/sentry-tunnel'
      path: '/api/sentry-tunnel'
      fullPath: '/api/sentry-tunnel'
      preLoaderRoute: typeof ApiSentryTunnelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/billing-bridge': {
      id: '/api/billing-bridge'
      path: '/api/billing-bridge'
      fullPath: '/api/billing-bridge'
      preLoaderRoute: typeof ApiBillingBridgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/playlists': {
      id: '/_authenticated/playlists'
      path: '/playlists'
      fullPath: '/playlists'
      preLoaderRoute: typeof AuthenticatedPlaylistsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/match': {
      id: '/_authenticated/match'
      path: '/match'
      fullPath: '/match'
      preLoaderRoute: typeof AuthenticatedMatchRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/liked-songs': {
      id: '/_authenticated/liked-songs'
      path: '/liked-songs'
      fullPath: '/liked-songs'
      preLoaderRoute: typeof AuthenticatedLikedSongsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/posthog/$': {
      id: '/api/posthog/$'
      path: '/api/posthog/$'
      fullPath: '/api/posthog/$'
      preLoaderRoute: typeof ApiPosthogSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/extension/token': {
      id: '/api/extension/token'
      path: '/api/extension/token'
      fullPath: '/api/extension/token'
      preLoaderRoute: typeof ApiExtensionTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/extension/sync': {
      id: '/api/extension/sync'
      path: '/api/extension/sync'
      fullPath: '/api/extension/sync'
      preLoaderRoute: typeof ApiExtensionSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/extension/status': {
      id: '/api/extension/status'
      path: '/api/extension/status'
      fullPath: '/api/extension/status'
      preLoaderRoute: typeof ApiExtensionStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/playlists/$playlistRef': {
      id: '/_authenticated/playlists/$playlistRef'
      path: '/$playlistRef'
      fullPath: '/playlists/$playlistRef'
      preLoaderRoute: typeof AuthenticatedPlaylistsPlaylistRefRouteImport
      parentRoute: typeof AuthenticatedPlaylistsRoute
    }
    '/_authenticated/checkout/success': {
      id: '/_authenticated/checkout/success'
      path: '/checkout/success'
      fullPath: '/checkout/success'
      preLoaderRoute: typeof AuthenticatedCheckoutSuccessRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/checkout/cancel': {
      id: '/_authenticated/checkout/cancel'
      path: '/checkout/cancel'
      fullPath: '/checkout/cancel'
      preLoaderRoute: typeof AuthenticatedCheckoutCancelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/extension/artists/check': {
      id: '/api/extension/artists/check'
      path: '/api/extension/artists/check'
      fullPath: '/api/extension/artists/check'
      preLoaderRoute: typeof ApiExtensionArtistsCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedPlaylistsRouteChildren {
  AuthenticatedPlaylistsPlaylistRefRoute: typeof AuthenticatedPlaylistsPlaylistRefRoute
}

const AuthenticatedPlaylistsRouteChildren: AuthenticatedPlaylistsRouteChildren =
  {
    AuthenticatedPlaylistsPlaylistRefRoute:
      AuthenticatedPlaylistsPlaylistRefRoute,
  }

const AuthenticatedPlaylistsRouteWithChildren =
  AuthenticatedPlaylistsRoute._addFileChildren(
    AuthenticatedPlaylistsRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedLikedSongsRoute: typeof AuthenticatedLikedSongsRoute
  AuthenticatedMatchRoute: typeof AuthenticatedMatchRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedPlaylistsRoute: typeof AuthenticatedPlaylistsRouteWithChildren
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedCheckoutCancelRoute: typeof AuthenticatedCheckoutCancelRoute
  AuthenticatedCheckoutSuccessRoute: typeof AuthenticatedCheckoutSuccessRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedLikedSongsRoute: AuthenticatedLikedSongsRoute,
  AuthenticatedMatchRoute: AuthenticatedMatchRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedPlaylistsRoute: AuthenticatedPlaylistsRouteWithChildren,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedCheckoutCancelRoute: AuthenticatedCheckoutCancelRoute,
  AuthenticatedCheckoutSuccessRoute: AuthenticatedCheckoutSuccessRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  FaqRoute: FaqRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HealthRoute: HealthRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TermsRoute: TermsRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  ApiBillingBridgeRoute: ApiBillingBridgeRoute,
  ApiSentryTunnelRoute: ApiSentryTunnelRoute,
  AuthLogoutRoute: AuthLogoutRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiExtensionStatusRoute: ApiExtensionStatusRoute,
  ApiExtensionSyncRoute: ApiExtensionSyncRoute,
  ApiExtensionTokenRoute: ApiExtensionTokenRoute,
  ApiPosthogSplatRoute: ApiPosthogSplatRoute,
  ApiExtensionArtistsCheckRoute: ApiExtensionArtistsCheckRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
