/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthLogoutRouteImport } from './routes/auth/logout'
import { Route as ApiArtistImagesForTracksRouteImport } from './routes/api/artist-images-for-tracks'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedPlaylistsRouteImport } from './routes/_authenticated/playlists'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedMatchRouteImport } from './routes/_authenticated/match'
import { Route as AuthenticatedLikedSongsRouteImport } from './routes/_authenticated/liked-songs'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthSpotifyRouteRouteImport } from './routes/auth/spotify/route'
import { Route as AuthSpotifyIndexRouteImport } from './routes/auth/spotify/index'
import { Route as AuthSpotifyCallbackRouteImport } from './routes/auth/spotify/callback'
import { Route as ApiJobsIdProgressRouteImport } from './routes/api/jobs/$id/progress'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLogoutRoute = AuthLogoutRouteImport.update({
  id: '/auth/logout',
  path: '/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiArtistImagesForTracksRoute =
  ApiArtistImagesForTracksRouteImport.update({
    id: '/api/artist-images-for-tracks',
    path: '/api/artist-images-for-tracks',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlaylistsRoute = AuthenticatedPlaylistsRouteImport.update({
  id: '/playlists',
  path: '/playlists',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMatchRoute = AuthenticatedMatchRouteImport.update({
  id: '/match',
  path: '/match',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLikedSongsRoute = AuthenticatedLikedSongsRouteImport.update({
  id: '/liked-songs',
  path: '/liked-songs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthSpotifyRouteRoute = AuthSpotifyRouteRouteImport.update({
  id: '/auth/spotify',
  path: '/auth/spotify',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSpotifyIndexRoute = AuthSpotifyIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthSpotifyRouteRoute,
} as any)
const AuthSpotifyCallbackRoute = AuthSpotifyCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthSpotifyRouteRoute,
} as any)
const ApiJobsIdProgressRoute = ApiJobsIdProgressRouteImport.update({
  id: '/api/jobs/$id/progress',
  path: '/api/jobs/$id/progress',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth/spotify': typeof AuthSpotifyRouteRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/liked-songs': typeof AuthenticatedLikedSongsRoute
  '/match': typeof AuthenticatedMatchRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/playlists': typeof AuthenticatedPlaylistsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/api/artist-images-for-tracks': typeof ApiArtistImagesForTracksRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/auth/spotify/callback': typeof AuthSpotifyCallbackRoute
  '/auth/spotify/': typeof AuthSpotifyIndexRoute
  '/api/jobs/$id/progress': typeof ApiJobsIdProgressRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/liked-songs': typeof AuthenticatedLikedSongsRoute
  '/match': typeof AuthenticatedMatchRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/playlists': typeof AuthenticatedPlaylistsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/api/artist-images-for-tracks': typeof ApiArtistImagesForTracksRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/auth/spotify/callback': typeof AuthSpotifyCallbackRoute
  '/auth/spotify': typeof AuthSpotifyIndexRoute
  '/api/jobs/$id/progress': typeof ApiJobsIdProgressRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth/spotify': typeof AuthSpotifyRouteRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/liked-songs': typeof AuthenticatedLikedSongsRoute
  '/_authenticated/match': typeof AuthenticatedMatchRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/playlists': typeof AuthenticatedPlaylistsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/api/artist-images-for-tracks': typeof ApiArtistImagesForTracksRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/auth/spotify/callback': typeof AuthSpotifyCallbackRoute
  '/auth/spotify/': typeof AuthSpotifyIndexRoute
  '/api/jobs/$id/progress': typeof ApiJobsIdProgressRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth/spotify'
    | '/dashboard'
    | '/liked-songs'
    | '/match'
    | '/onboarding'
    | '/playlists'
    | '/settings'
    | '/api/artist-images-for-tracks'
    | '/auth/logout'
    | '/auth/spotify/callback'
    | '/auth/spotify/'
    | '/api/jobs/$id/progress'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/liked-songs'
    | '/match'
    | '/onboarding'
    | '/playlists'
    | '/settings'
    | '/api/artist-images-for-tracks'
    | '/auth/logout'
    | '/auth/spotify/callback'
    | '/auth/spotify'
    | '/api/jobs/$id/progress'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth/spotify'
    | '/_authenticated/dashboard'
    | '/_authenticated/liked-songs'
    | '/_authenticated/match'
    | '/_authenticated/onboarding'
    | '/_authenticated/playlists'
    | '/_authenticated/settings'
    | '/api/artist-images-for-tracks'
    | '/auth/logout'
    | '/auth/spotify/callback'
    | '/auth/spotify/'
    | '/api/jobs/$id/progress'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthSpotifyRouteRoute: typeof AuthSpotifyRouteRouteWithChildren
  ApiArtistImagesForTracksRoute: typeof ApiArtistImagesForTracksRoute
  AuthLogoutRoute: typeof AuthLogoutRoute
  ApiJobsIdProgressRoute: typeof ApiJobsIdProgressRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/logout': {
      id: '/auth/logout'
      path: '/auth/logout'
      fullPath: '/auth/logout'
      preLoaderRoute: typeof AuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/artist-images-for-tracks': {
      id: '/api/artist-images-for-tracks'
      path: '/api/artist-images-for-tracks'
      fullPath: '/api/artist-images-for-tracks'
      preLoaderRoute: typeof ApiArtistImagesForTracksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/playlists': {
      id: '/_authenticated/playlists'
      path: '/playlists'
      fullPath: '/playlists'
      preLoaderRoute: typeof AuthenticatedPlaylistsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/match': {
      id: '/_authenticated/match'
      path: '/match'
      fullPath: '/match'
      preLoaderRoute: typeof AuthenticatedMatchRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/liked-songs': {
      id: '/_authenticated/liked-songs'
      path: '/liked-songs'
      fullPath: '/liked-songs'
      preLoaderRoute: typeof AuthenticatedLikedSongsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/auth/spotify': {
      id: '/auth/spotify'
      path: '/auth/spotify'
      fullPath: '/auth/spotify'
      preLoaderRoute: typeof AuthSpotifyRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/spotify/': {
      id: '/auth/spotify/'
      path: '/'
      fullPath: '/auth/spotify/'
      preLoaderRoute: typeof AuthSpotifyIndexRouteImport
      parentRoute: typeof AuthSpotifyRouteRoute
    }
    '/auth/spotify/callback': {
      id: '/auth/spotify/callback'
      path: '/callback'
      fullPath: '/auth/spotify/callback'
      preLoaderRoute: typeof AuthSpotifyCallbackRouteImport
      parentRoute: typeof AuthSpotifyRouteRoute
    }
    '/api/jobs/$id/progress': {
      id: '/api/jobs/$id/progress'
      path: '/api/jobs/$id/progress'
      fullPath: '/api/jobs/$id/progress'
      preLoaderRoute: typeof ApiJobsIdProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedLikedSongsRoute: typeof AuthenticatedLikedSongsRoute
  AuthenticatedMatchRoute: typeof AuthenticatedMatchRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedPlaylistsRoute: typeof AuthenticatedPlaylistsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedLikedSongsRoute: AuthenticatedLikedSongsRoute,
  AuthenticatedMatchRoute: AuthenticatedMatchRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedPlaylistsRoute: AuthenticatedPlaylistsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AuthSpotifyRouteRouteChildren {
  AuthSpotifyCallbackRoute: typeof AuthSpotifyCallbackRoute
  AuthSpotifyIndexRoute: typeof AuthSpotifyIndexRoute
}

const AuthSpotifyRouteRouteChildren: AuthSpotifyRouteRouteChildren = {
  AuthSpotifyCallbackRoute: AuthSpotifyCallbackRoute,
  AuthSpotifyIndexRoute: AuthSpotifyIndexRoute,
}

const AuthSpotifyRouteRouteWithChildren =
  AuthSpotifyRouteRoute._addFileChildren(AuthSpotifyRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthSpotifyRouteRoute: AuthSpotifyRouteRouteWithChildren,
  ApiArtistImagesForTracksRoute: ApiArtistImagesForTracksRoute,
  AuthLogoutRoute: AuthLogoutRoute,
  ApiJobsIdProgressRoute: ApiJobsIdProgressRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
