/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthSpotifyRouteImport } from './routes/auth/spotify'
import { Route as AuthLogoutRouteImport } from './routes/auth/logout'
import { Route as AuthSpotifyIndexRouteImport } from './routes/auth/spotify.index'
import { Route as AuthSpotifyCallbackRouteImport } from './routes/auth/spotify.callback'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSpotifyRoute = AuthSpotifyRouteImport.update({
  id: '/auth/spotify',
  path: '/auth/spotify',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLogoutRoute = AuthLogoutRouteImport.update({
  id: '/auth/logout',
  path: '/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSpotifyIndexRoute = AuthSpotifyIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthSpotifyRoute,
} as any)
const AuthSpotifyCallbackRoute = AuthSpotifyCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthSpotifyRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/auth/spotify': typeof AuthSpotifyRouteWithChildren
  '/auth/spotify/callback': typeof AuthSpotifyCallbackRoute
  '/auth/spotify/': typeof AuthSpotifyIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/auth/spotify/callback': typeof AuthSpotifyCallbackRoute
  '/auth/spotify': typeof AuthSpotifyIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/auth/spotify': typeof AuthSpotifyRouteWithChildren
  '/auth/spotify/callback': typeof AuthSpotifyCallbackRoute
  '/auth/spotify/': typeof AuthSpotifyIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth/logout'
    | '/auth/spotify'
    | '/auth/spotify/callback'
    | '/auth/spotify/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth/logout' | '/auth/spotify/callback' | '/auth/spotify'
  id:
    | '__root__'
    | '/'
    | '/auth/logout'
    | '/auth/spotify'
    | '/auth/spotify/callback'
    | '/auth/spotify/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthLogoutRoute: typeof AuthLogoutRoute
  AuthSpotifyRoute: typeof AuthSpotifyRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/spotify': {
      id: '/auth/spotify'
      path: '/auth/spotify'
      fullPath: '/auth/spotify'
      preLoaderRoute: typeof AuthSpotifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/logout': {
      id: '/auth/logout'
      path: '/auth/logout'
      fullPath: '/auth/logout'
      preLoaderRoute: typeof AuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/spotify/': {
      id: '/auth/spotify/'
      path: '/'
      fullPath: '/auth/spotify/'
      preLoaderRoute: typeof AuthSpotifyIndexRouteImport
      parentRoute: typeof AuthSpotifyRoute
    }
    '/auth/spotify/callback': {
      id: '/auth/spotify/callback'
      path: '/callback'
      fullPath: '/auth/spotify/callback'
      preLoaderRoute: typeof AuthSpotifyCallbackRouteImport
      parentRoute: typeof AuthSpotifyRoute
    }
  }
}

interface AuthSpotifyRouteChildren {
  AuthSpotifyCallbackRoute: typeof AuthSpotifyCallbackRoute
  AuthSpotifyIndexRoute: typeof AuthSpotifyIndexRoute
}

const AuthSpotifyRouteChildren: AuthSpotifyRouteChildren = {
  AuthSpotifyCallbackRoute: AuthSpotifyCallbackRoute,
  AuthSpotifyIndexRoute: AuthSpotifyIndexRoute,
}

const AuthSpotifyRouteWithChildren = AuthSpotifyRoute._addFileChildren(
  AuthSpotifyRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthLogoutRoute: AuthLogoutRoute,
  AuthSpotifyRoute: AuthSpotifyRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
