-- Preprod posture: public-schema RPCs are backend-private and should only be
-- callable through the service-role client used by the app server and worker.

REVOKE EXECUTE ON FUNCTION
  public.activate_subscription(UUID, TEXT, TEXT, TEXT, TIMESTAMPTZ),
  public.activate_unlimited_songs(UUID, TEXT, TIMESTAMPTZ),
  public.apply_subscription_upgrade_conversion(UUID, TEXT, TEXT, TEXT),
  public.claim_billing_bridge_event(TEXT, TEXT, INTEGER),
  public.claim_pending_library_processing_job(),
  public.claim_pending_lightweight_enrichment_job(),
  public.claim_pending_rematch_job(),
  public.claim_pending_walkthrough_preview_job(),
  public.count_analyzed_songs_for_account(UUID),
  public.count_unresolved_job_item_failures(UUID, UUID, TEXT, TEXT),
  public.deactivate_subscription(UUID),
  public.fulfill_pack_purchase(UUID, TEXT, TEXT, INTEGER, INTEGER),
  public.get_library_artist_count(UUID),
  public.get_liked_songs_page(UUID, TIMESTAMPTZ, INTEGER, TEXT),
  public.get_liked_songs_stats(UUID),
  public.grant_analysis_failure_replacement_credit(UUID, UUID, TEXT),
  public.grant_credits(UUID, INTEGER, TEXT, TEXT),
  public.insert_song_unlocks_without_charge(UUID, UUID[], TEXT, TEXT),
  public.is_account_song_entitled(UUID, UUID),
  public.link_subscription_upgrade_checkout(UUID, TEXT),
  public.mark_billing_bridge_event_failed(TEXT, TEXT),
  public.mark_billing_bridge_event_processed(TEXT),
  public.mark_dead_library_processing_jobs(INTERVAL),
  public.mark_dead_rematch_jobs(INTERVAL),
  public.mark_dead_walkthrough_preview_jobs(INTERVAL),
  public.prepare_subscription_upgrade_conversion(UUID, TEXT),
  public.publish_match_snapshot(UUID, TEXT, TEXT, TEXT, TEXT, TEXT, INTEGER, INTEGER, JSONB),
  public.quote_subscription_upgrade_conversion(UUID),
  public.release_subscription_upgrade_conversion(UUID),
  public.reprioritize_pending_jobs_for_account(UUID),
  public.resolve_job_item_stage_failures(UUID, UUID, TEXT),
  public.reverse_pack_entitlement(UUID, TEXT, TEXT, TEXT),
  public.reverse_subscription_upgrade_conversion(UUID, TEXT),
  public.reverse_unlimited_period_entitlement(TEXT, TIMESTAMPTZ, TEXT, TEXT),
  public.select_data_enriched_liked_song_ids(UUID),
  public.select_entitled_data_enriched_liked_song_ids(UUID),
  public.select_liked_song_ids_needing_enrichment_work(UUID, INTEGER),
  public.select_liked_song_ids_needing_pipeline_processing(UUID, INTEGER),
  public.sweep_stale_library_processing_jobs(INTERVAL),
  public.sweep_stale_rematch_jobs(INTERVAL),
  public.sweep_stale_walkthrough_preview_jobs(INTERVAL),
  public.unlock_songs_for_account(UUID, UUID[]),
  public.update_subscription_state(UUID, TEXT, TIMESTAMPTZ, BOOLEAN)
FROM PUBLIC, anon, authenticated;

GRANT EXECUTE ON FUNCTION
  public.activate_subscription(UUID, TEXT, TEXT, TEXT, TIMESTAMPTZ),
  public.activate_unlimited_songs(UUID, TEXT, TIMESTAMPTZ),
  public.apply_subscription_upgrade_conversion(UUID, TEXT, TEXT, TEXT),
  public.claim_billing_bridge_event(TEXT, TEXT, INTEGER),
  public.claim_pending_library_processing_job(),
  public.claim_pending_lightweight_enrichment_job(),
  public.claim_pending_rematch_job(),
  public.claim_pending_walkthrough_preview_job(),
  public.count_analyzed_songs_for_account(UUID),
  public.count_unresolved_job_item_failures(UUID, UUID, TEXT, TEXT),
  public.deactivate_subscription(UUID),
  public.fulfill_pack_purchase(UUID, TEXT, TEXT, INTEGER, INTEGER),
  public.get_library_artist_count(UUID),
  public.get_liked_songs_page(UUID, TIMESTAMPTZ, INTEGER, TEXT),
  public.get_liked_songs_stats(UUID),
  public.grant_analysis_failure_replacement_credit(UUID, UUID, TEXT),
  public.grant_credits(UUID, INTEGER, TEXT, TEXT),
  public.insert_song_unlocks_without_charge(UUID, UUID[], TEXT, TEXT),
  public.is_account_song_entitled(UUID, UUID),
  public.link_subscription_upgrade_checkout(UUID, TEXT),
  public.mark_billing_bridge_event_failed(TEXT, TEXT),
  public.mark_billing_bridge_event_processed(TEXT),
  public.mark_dead_library_processing_jobs(INTERVAL),
  public.mark_dead_rematch_jobs(INTERVAL),
  public.mark_dead_walkthrough_preview_jobs(INTERVAL),
  public.prepare_subscription_upgrade_conversion(UUID, TEXT),
  public.publish_match_snapshot(UUID, TEXT, TEXT, TEXT, TEXT, TEXT, INTEGER, INTEGER, JSONB),
  public.quote_subscription_upgrade_conversion(UUID),
  public.release_subscription_upgrade_conversion(UUID),
  public.reprioritize_pending_jobs_for_account(UUID),
  public.resolve_job_item_stage_failures(UUID, UUID, TEXT),
  public.reverse_pack_entitlement(UUID, TEXT, TEXT, TEXT),
  public.reverse_subscription_upgrade_conversion(UUID, TEXT),
  public.reverse_unlimited_period_entitlement(TEXT, TIMESTAMPTZ, TEXT, TEXT),
  public.select_data_enriched_liked_song_ids(UUID),
  public.select_entitled_data_enriched_liked_song_ids(UUID),
  public.select_liked_song_ids_needing_enrichment_work(UUID, INTEGER),
  public.select_liked_song_ids_needing_pipeline_processing(UUID, INTEGER),
  public.sweep_stale_library_processing_jobs(INTERVAL),
  public.sweep_stale_rematch_jobs(INTERVAL),
  public.sweep_stale_walkthrough_preview_jobs(INTERVAL),
  public.unlock_songs_for_account(UUID, UUID[]),
  public.update_subscription_state(UUID, TEXT, TIMESTAMPTZ, BOOLEAN)
TO service_role;

ALTER TABLE public.billing_admin_task ENABLE ROW LEVEL SECURITY;

ALTER FUNCTION public.claim_pending_walkthrough_preview_job() SET search_path = public;
ALTER FUNCTION public.sweep_stale_walkthrough_preview_jobs(INTERVAL) SET search_path = public;
ALTER FUNCTION public.mark_dead_walkthrough_preview_jobs(INTERVAL) SET search_path = public;
ALTER FUNCTION public.publish_match_snapshot(UUID, TEXT, TEXT, TEXT, TEXT, TEXT, INTEGER, INTEGER, JSONB) SET search_path = public;
ALTER FUNCTION public.get_library_artist_count(UUID) SET search_path = public;
